// ============================================================
// MUMI AMAZONIA — Biblioteca de frases motivacionales y de emprendimiento
// Se muestra una frase distinta cada día en el Tablero Principal.
// ============================================================

export const FRASES = [
  { texto: 'El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.', autor: 'Albert Schweitzer' },
  { texto: 'Empieza donde estás. Usa lo que tienes. Haz lo que puedas.', autor: 'Arthur Ashe' },
  { texto: 'No esperes el momento perfecto. Toma el momento y hazlo perfecto.', autor: 'Anónimo' },
  { texto: 'La mejor forma de predecir el futuro es creándolo.', autor: 'Peter Drucker' },
  { texto: 'El secreto para salir adelante es comenzar.', autor: 'Mark Twain' },
  { texto: 'Si puedes soñarlo, puedes lograrlo.', autor: 'Walt Disney' },
  { texto: 'Los grandes logros nacen de pequeños esfuerzos repetidos día tras día.', autor: 'Robert Collier' },
  { texto: 'El que no arriesga, no gana.', autor: 'Refrán popular' },
  { texto: 'La disciplina es el puente entre las metas y los logros.', autor: 'Jim Rohn' },
  { texto: 'Haz de cada día tu obra maestra.', autor: 'John Wooden' },
  { texto: 'No cuentes los días, haz que los días cuenten.', autor: 'Muhammad Ali' },
  { texto: 'El emprendedor siempre busca el cambio, responde a él y lo explota como una oportunidad.', autor: 'Peter Drucker' },
  { texto: 'La calidad nunca es un accidente; siempre es el resultado de un esfuerzo inteligente.', autor: 'John Ruskin' },
  { texto: 'Tu trabajo va a llenar gran parte de tu vida; la única forma de estar satisfecho es hacer lo que crees que es un gran trabajo.', autor: 'Steve Jobs' },
  { texto: 'El fracaso es simplemente la oportunidad de comenzar de nuevo, esta vez de forma más inteligente.', autor: 'Henry Ford' },
  { texto: 'No te preocupes por los fracasos, preocúpate por las oportunidades que pierdes cuando ni siquiera lo intentas.', autor: 'Jack Canfield' },
  { texto: 'Las oportunidades no ocurren, las creas tú.', autor: 'Chris Grosser' },
  { texto: 'El único lugar donde el éxito viene antes que el trabajo es en el diccionario.', autor: 'Vidal Sassoon' },
  { texto: 'Cae siete veces, levántate ocho.', autor: 'Proverbio japonés' },
  { texto: 'La constancia vence lo que la dicha no alcanza.', autor: 'Refrán popular' },
  { texto: 'No hay ascensor hacia el éxito, hay que subir por las escaleras.', autor: 'Zig Ziglar' },
  { texto: 'Cree que puedes y ya estás a medio camino.', autor: 'Theodore Roosevelt' },
  { texto: 'El riesgo viene de no saber lo que estás haciendo.', autor: 'Warren Buffett' },
  { texto: 'Una meta sin un plan es solo un deseo.', autor: 'Antoine de Saint-Exupéry' },
  { texto: 'Lo que haces hoy puede mejorar todos tus mañanas.', autor: 'Ralph Marston' },
  { texto: 'El trabajo duro vence al talento cuando el talento no trabaja duro.', autor: 'Tim Notke' },
  { texto: 'No sueñes tu vida, vive tu sueño.', autor: 'Anónimo' },
  { texto: 'La perseverancia es fracasar 19 veces y tener éxito en la veinte.', autor: 'Julie Andrews' },
  { texto: 'El éxito es ir de fracaso en fracaso sin perder el entusiasmo.', autor: 'Winston Churchill' },
  { texto: 'Si quieres algo que nunca has tenido, debes hacer algo que nunca has hecho.', autor: 'Thomas Jefferson' },
  { texto: 'Las grandes cosas nunca vienen de la zona de confort.', autor: 'Anónimo' },
  { texto: 'El emprendimiento es vivir unos años de tu vida como la mayoría no lo haría, para vivir el resto como la mayoría no podría.', autor: 'Anónimo' },
  { texto: 'No midas tu progreso con la vara de otra persona.', autor: 'H. Jackson Brown' },
  { texto: 'Convierte tus heridas en sabiduría.', autor: 'Oprah Winfrey' },
  { texto: 'El optimismo es la fe que conduce al logro.', autor: 'Helen Keller' },
  { texto: 'Hazlo con pasión o no lo hagas.', autor: 'Rosa Nouchi' },
  { texto: 'Cada experto fue alguna vez un principiante.', autor: 'Helen Hayes' },
  { texto: 'La acción es la clave fundamental de todo éxito.', autor: 'Pablo Picasso' },
  { texto: 'No busques que las cosas sean más fáciles, busca ser mejor.', autor: 'Jim Rohn' },
  { texto: 'El que tiene un porqué para vivir puede soportar casi cualquier cómo.', autor: 'Friedrich Nietzsche' },
  { texto: 'La motivación te impulsa a comenzar; el hábito te mantiene en marcha.', autor: 'Jim Ryun' },
  { texto: 'Sueña en grande y atrévete a fracasar.', autor: 'Norman Vaughan' },
  { texto: 'No esperes oportunidades extraordinarias. Aprovecha las ocasiones comunes y hazlas grandes.', autor: 'Orison Swett Marden' },
  { texto: 'Lo difícil es lo que toma un poco de tiempo; lo imposible, un poco más.', autor: 'André Jackson' },
  { texto: 'El secreto del progreso es comenzar.', autor: 'Mark Twain' },
  { texto: 'Trabaja en silencio y deja que tu éxito haga el ruido.', autor: 'Anónimo' },
  { texto: 'La pasión es energía. Siente el poder que viene de enfocarte en lo que te emociona.', autor: 'Oprah Winfrey' },
  { texto: 'Si no construyes tu sueño, alguien te contratará para construir el suyo.', autor: 'Tony Gaskins' },
  { texto: 'El éxito generalmente llega a quienes están demasiado ocupados buscándolo.', autor: 'Henry David Thoreau' },
  { texto: 'No te rindas. Sufre ahora y vive el resto de tu vida como un campeón.', autor: 'Muhammad Ali' },
  { texto: 'La innovación distingue a un líder de un seguidor.', autor: 'Steve Jobs' },
  { texto: 'Hecho es mejor que perfecto.', autor: 'Sheryl Sandberg' },
  { texto: 'El cliente más insatisfecho es tu mayor fuente de aprendizaje.', autor: 'Bill Gates' },
  { texto: 'Crea algo que la gente quiera.', autor: 'Paul Graham' },
  { texto: 'Tu marca es lo que la gente dice de ti cuando no estás en la habitación.', autor: 'Jeff Bezos' },
  { texto: 'No tienes que ser grande para empezar, pero tienes que empezar para ser grande.', autor: 'Zig Ziglar' },
  { texto: 'El precio se olvida, la calidad permanece.', autor: 'Aldo Gucci' },
  { texto: 'Empieza pequeño, piensa en grande.', autor: 'Anónimo' },
  { texto: 'Las ideas son fáciles. La ejecución lo es todo.', autor: 'John Doerr' },
  { texto: 'La paciencia y la perseverancia tienen un efecto mágico ante el cual las dificultades desaparecen.', autor: 'John Quincy Adams' },
  { texto: 'No dejes que el miedo a perder sea mayor que la emoción de ganar.', autor: 'Robert Kiyosaki' },
  { texto: 'El dinero es un excelente sirviente, pero un pésimo amo.', autor: 'Francis Bacon' },
  { texto: 'Invierte en ti mismo. Es la mejor inversión que harás.', autor: 'Anónimo' },
  { texto: 'Una persona que nunca cometió un error nunca intentó algo nuevo.', autor: 'Albert Einstein' },
  { texto: 'La excelencia no es un acto, sino un hábito.', autor: 'Aristóteles' },
  { texto: 'Cuanto más duro trabajo, más suerte tengo.', autor: 'Samuel Goldwyn' },
  { texto: 'No se trata de tener tiempo, se trata de hacer tiempo.', autor: 'Anónimo' },
  { texto: 'El crecimiento y la comodidad no coexisten.', autor: 'Ginni Rometty' },
  { texto: 'Rodéate de quienes te empujen a ser mejor.', autor: 'Anónimo' },
  { texto: 'El que mucho abarca poco aprieta; enfócate.', autor: 'Refrán popular' },
  { texto: 'La mejor venganza es un éxito masivo.', autor: 'Frank Sinatra' },
  { texto: 'Donde hay una empresa de éxito, alguien tomó alguna vez una decisión valiente.', autor: 'Peter Drucker' },
  { texto: 'El emprendedor ve oportunidad donde otros ven problema.', autor: 'Anónimo' },
  { texto: 'No persigas el dinero, persigue la excelencia y el dinero te seguirá.', autor: 'Anónimo' },
  { texto: 'Cada gran sueño comienza con un soñador.', autor: 'Harriet Tubman' },
  { texto: 'La vida es 10% lo que te pasa y 90% cómo reaccionas a ello.', autor: 'Charles Swindoll' },
  { texto: 'Quien quiere hacer algo encuentra un medio; quien no, una excusa.', autor: 'Refrán árabe' },
  { texto: 'El éxito es la suma de pequeños esfuerzos repetidos día tras día.', autor: 'Robert Collier' },
  { texto: 'Atrévete a ser diferente y a marcar tu propio camino.', autor: 'Anónimo' },
  { texto: 'La mejor inversión es en tus propias habilidades.', autor: 'Warren Buffett' },
  { texto: 'No tengas miedo de renunciar a lo bueno para ir por lo grandioso.', autor: 'John D. Rockefeller' },
  { texto: 'Un objetivo bien definido es la mitad del trabajo realizado.', autor: 'Anónimo' },
  { texto: 'El liderazgo es la capacidad de transformar la visión en realidad.', autor: 'Warren Bennis' },
  { texto: 'Si la oportunidad no llama, construye una puerta.', autor: 'Milton Berle' },
  { texto: 'Nunca es demasiado tarde para ser lo que podrías haber sido.', autor: 'George Eliot' },
  { texto: 'El conocimiento es la nueva moneda del éxito.', autor: 'Anónimo' },
  { texto: 'Haz hoy lo que otros no quieren, para tener mañana lo que otros no tendrán.', autor: 'Anónimo' },
  { texto: 'La energía y la persistencia conquistan todas las cosas.', autor: 'Benjamin Franklin' },
  { texto: 'Trabaja para construir tu propio sueño, o alguien te contratará para construir el suyo.', autor: 'Farrah Gray' },
  { texto: 'La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.', autor: 'Jimmy Johnson' },
  { texto: 'No mires el reloj; haz lo que él hace: sigue avanzando.', autor: 'Sam Levenson' },
  { texto: 'Tu actitud, no tu aptitud, determinará tu altitud.', autor: 'Zig Ziglar' },
  { texto: 'El esfuerzo de hoy es el resultado de mañana.', autor: 'Anónimo' },
  { texto: 'Quien teme sufrir, ya sufre el temor.', autor: 'Proverbio chino' },
  { texto: 'Los sueños no funcionan a menos que tú trabajes.', autor: 'John C. Maxwell' },
  { texto: 'Aprende como si fueras a vivir para siempre, vive como si fueras a morir mañana.', autor: 'Mahatma Gandhi' },
  { texto: 'La creatividad es la inteligencia divirtiéndose.', autor: 'Albert Einstein' },
  { texto: 'El que no vive para servir, no sirve para vivir.', autor: 'Madre Teresa de Calcuta' },
  { texto: 'Pequeños pasos cada día construyen grandes resultados.', autor: 'Anónimo' },
  { texto: 'No esperes a sentirte listo. La acción genera confianza.', autor: 'Anónimo' },
  { texto: 'El verdadero emprendedor convierte los obstáculos en escalones.', autor: 'Anónimo' },
  { texto: 'La fe en uno mismo es el primer secreto del éxito.', autor: 'Ralph Waldo Emerson' },
  { texto: 'Vende soluciones, no productos.', autor: 'Anónimo' },
  { texto: 'Cada No te acerca a un gran Sí.', autor: 'Anónimo' },
  { texto: 'El verdadero progreso es el que pone la tecnología al alcance de todos.', autor: 'Henry Ford' },
  { texto: 'Quien domina su tiempo, domina su vida.', autor: 'Anónimo' },
  { texto: 'La reputación se construye con acciones, no con palabras.', autor: 'Anónimo' },
  { texto: 'Sé tan bueno que no puedan ignorarte.', autor: 'Steve Martin' },
  { texto: 'El primer paso para ganar es decidir que no vas a perder.', autor: 'Anónimo' },
  { texto: 'Lo que siembras hoy lo cosechas mañana.', autor: 'Refrán popular' },
  { texto: 'La mejor publicidad es la que hacen los clientes satisfechos.', autor: 'Philip Kotler' },
  { texto: 'Hazlo, y si no sale bien, hazlo de nuevo mejor.', autor: 'Anónimo' },
  { texto: 'El que se atreve a enseñar nunca debe dejar de aprender.', autor: 'John Cotton Dana' },
  { texto: 'La grandeza está en hacer cosas pequeñas con un gran corazón.', autor: 'Anónimo' },
  { texto: 'Tus límites son solo tu imaginación.', autor: 'Anónimo' },
  { texto: 'No cuentes lo que vas a hacer; hazlo y deja que los resultados hablen.', autor: 'Anónimo' },
]

// Devuelve la frase del día (estable durante todo el día, distinta cada día)
export function fraseDelDia(fecha = new Date()) {
  // Día del año (1–366) para rotar sobre el arreglo
  const inicio = new Date(fecha.getFullYear(), 0, 0)
  const diff = fecha - inicio
  const dia = Math.floor(diff / (1000 * 60 * 60 * 24))
  return FRASES[dia % FRASES.length]
}
