-- v139 — Órdenes manuales, alertas de fichas y depreciación centralizada.

alter table products_costing
  add column if not exists empaca_surtido boolean not null default false,
  add column if not exists costos_hora jsonb not null default '[]'::jsonb,
  add column if not exists equipo_unit numeric not null default 0;

comment on column products_costing.costos_hora is
  'Costos operativos por duración: [{nombre, unidad: hora|dia, tarifa, cantidad_default}].';

alter table production_orders
  add column if not exists orden_blanca boolean not null default false,
  add column if not exists ingredientes_manual jsonb not null default '[]'::jsonb,
  add column if not exists costos_adicionales_hora jsonb not null default '[]'::jsonb,
  add column if not exists costo_snapshot jsonb;

comment on column production_orders.ingredientes_manual is
  'Ingredientes definidos en el diligenciamiento de una orden blanca.';
comment on column production_orders.costo_snapshot is
  'Costo congelado al cerrar: ficha, real, desviación y desglose.';

create table if not exists ficha_alert_dismissals (
  id bigint generated by default as identity primary key,
  product_id bigint not null references products_costing(id) on delete cascade,
  alert_type text not null check (alert_type in ('baches_mes', 'costo_desviacion')),
  periodo text not null check (periodo ~ '^[0-9]{4}-[0-9]{2}$'),
  dismissed_by text,
  dismissed_at timestamptz not null default now(),
  unique (product_id, alert_type, periodo)
);

create index if not exists idx_ficha_alert_dismissals_producto_periodo
  on ficha_alert_dismissals(product_id, periodo);

create table if not exists equipment_assets (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text not null default '',
  valor_adquisicion numeric not null default 0 check (valor_adquisicion >= 0),
  valor_residual numeric not null default 0 check (valor_residual >= 0),
  vida_util_anos numeric not null default 5 check (vida_util_anos > 0),
  fecha_adquisicion date,
  allocation_mode text not null default 'general'
    check (allocation_mode in ('general', 'categoria')),
  rate_basis text check (rate_basis in ('hora', 'dia')),
  capacidad_mes numeric check (capacidad_mes is null or capacidad_mes > 0),
  grupo text not null default 'cif'
    check (grupo in ('cif','administracion','ventas','financiero','impuesto','pasivo')),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (valor_residual <= valor_adquisicion),
  check (
    allocation_mode = 'general'
    or (allocation_mode = 'categoria' and rate_basis is not null and capacidad_mes > 0)
  )
);

create table if not exists equipment_category_links (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references equipment_assets(id) on delete cascade,
  categoria text not null,
  unique (equipment_id, categoria)
);

create index if not exists idx_equipment_category_links_categoria
  on equipment_category_links(categoria);

alter table ficha_alert_dismissals enable row level security;
alter table equipment_assets enable row level security;
alter table equipment_category_links enable row level security;

drop policy if exists "ficha_alert_dismissals_select" on ficha_alert_dismissals;
create policy "ficha_alert_dismissals_select" on ficha_alert_dismissals
  for select to authenticated using (true);
drop policy if exists "ficha_alert_dismissals_write" on ficha_alert_dismissals;
create policy "ficha_alert_dismissals_write" on ficha_alert_dismissals
  for all to authenticated using (true) with check (true);

drop policy if exists "equipment_assets_select" on equipment_assets;
create policy "equipment_assets_select" on equipment_assets
  for select to authenticated using (true);
drop policy if exists "equipment_assets_admin" on equipment_assets;
create policy "equipment_assets_admin" on equipment_assets
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "equipment_category_links_select" on equipment_category_links;
create policy "equipment_category_links_select" on equipment_category_links
  for select to authenticated using (true);
drop policy if exists "equipment_category_links_admin" on equipment_category_links;
create policy "equipment_category_links_admin" on equipment_category_links
  for all to authenticated using (public.is_admin()) with check (public.is_admin());
